### PR TITLE
Create Simplified_Chinese

### PR DESCRIPTION
**Pull request by SuperCirno**
Simplified Chinese

### CODE REVIEW

**Comment by SuperCirno** [comment]
@2TallTyler hi, I want to test before submitting it, but how can I put this file into grf?

**Comment by 2TallTyler** [comment]
You'll need to build and install the NML compiler NMLC from [its source on GitHub](https://github.com/OpenTTD/nml). There is a self-contained release, but it's rather out-of-date and this NewGRF uses several features not in the release, thus the need to build it yourself (it's pretty easy). You will also need to add the compiler to your system path so you can call it simply by typing `nmlc` into the command line. Then you can run this repository's Python script `make.py`, which will assemble the source code and compile it using the compiler.

Or, I'm happy to build it for you:
[SuperCirno_improved_town_industries.zip](https://github.com/2TallTyler/improved_town_industries/files/6273280/SuperCirno_improved_town_industries.zip)

**Comment by SuperCirno** [comment]
Thank you so much! ! !

**Comment by James103** [comment]
For consistency, can you please change the file name to `simplified_chinese.lng` and the first line to `##grflangid 0x56`?

**Comment by SuperCirno** [comment]
> For consistency, can you please change the file name to `simplified_chinese.lng` and the first line to `##grflangid 0x56`?

oh sry , I was wrong

**Comment by SuperCirno** [comment]
It looks like it can be used normally, there is nothing missing

**Comment by 2TallTyler** [comment]
Let me know when you're done with this, and I'll merge it. :)

**Comment by SuperCirno** [comment]
I finished

**Review by 2TallTyler — APPROVED** [review]

**Comment by 2TallTyler** [comment]
Thanks! This is in 1.7.4, now available on Bananas.

**Pull request merged**
